name: Keep Render REST API Alive

on:
    schedule:
        - cron: '*/6 * * * *' # Каждые 6 минут (GitHub позволяет)

    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest

        timeout-minutes: 2

        steps:
            - name: Ping API

              run: |

                  curl -sSf "https://ufc-api-7z3p.onrender.com" \

                    --max-time 5 \

                    --retry 1 \

                    --write-out "Status: %{http_code}\n"
