name: UFC Parser
on:
    schedule:
        - cron: '0 23 * * *' # Запуск каждый день в 03:00 по МСК
    push:
        branches:
            - main # Срабатывает при push в main
    workflow_dispatch: # Ручной запуск (опционально)

jobs:
    run-parser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install Chromium
              run: |
                  sudo apt-get update
                  sudo apt-get install -y chromium
                  echo "CHROME_PATH=/usr/bin/chromium" >> $GITHUB_ENV

            - name: Verify project structure
              run: |
                  echo "Содержимое src/utils:"
                  ls -la src/utils/
                  echo "Поиск файла парсера:"
                  find . -name "parsersUfC.ts"

            - name: Run Parser with Retry
              env:
                  DATABASE: ${{ secrets.DATABASE }}
              run: |
                  npm install
                  MAX_RETRIES=5  # Максимум 5 попыток (можно изменить)
                  ATTEMPT=1
                  SUCCESS=false

                  while [ $ATTEMPT -le $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
                      echo "Попытка $ATTEMPT из $MAX_RETRIES..."
                      if npx ts-node src/utils/parsersUFC.ts; then
                          echo "✅ Парсер успешно завершен!"
                          SUCCESS=true
                      else
                          echo "❌ Ошибка в попытке $ATTEMPT. Ждем 10 секунд перед повторным запуском..."
                          sleep 10
                          ((ATTEMPT++))
                      fi
                  done

                  if [ "$SUCCESS" = false ]; then
                      echo "🚨 Все попытки завершились ошибкой!"
                      exit 1
                  fi
